In [1]:
import numpy as np

# Create a 1-D NumPy array
arr = np.array([10, 20, 30, 40, 50])

print("Original Array:")
print(arr)

# Add 2 to every element
result = arr + 2

print("After adding 2:")
print(result)

Original Array:
[10 20 30 40 50]
After adding 2:
[12 22 32 42 52]


In [2]:
import numpy as np

# Create a 1-D NumPy array
arr = np.array([10, 20, 30, 40, 50])

print("Original Array:")
print(arr)

# Multiply every element by 3
result = arr * 3

print("After multiplying by 3:")
print(result)

Original Array:
[10 20 30 40 50]
After multiplying by 3:
[ 30  60  90 120 150]


In [3]:
import numpy as np

# Create a 1-D NumPy array
arr = np.array([10, 20, 30, 40, 50])

print("Original Array:")
print(arr)

# Divide every element by 2
result = arr / 2

print("After dividing by 2:")
print(result)

Original Array:
[10 20 30 40 50]
After dividing by 2:
[ 5. 10. 15. 20. 25.]


In [4]:
import numpy as np

# Create the NumPy array
arr = np.array([1, 2, 3, 6, 4, 5])

print("Original Array:")
print(arr)

# Reverse the array
reverse_arr = arr[::-1]

print("Reversed Array:")
print(reverse_arr)

Original Array:
[1 2 3 6 4 5]
Reversed Array:
[5 4 6 3 2 1]


In [11]:
#x = np.array([1,2,3,4,5,1,2,1,1,1])  
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

# Find unique values and their counts
values, counts = np.unique(x, return_counts=True)

# Find the value with the highest frequency
most_frequent = values[np.argmax(counts)]

# Find the indices of the most frequent value
indices = np.where(x == most_frequent)[0]

print("Array x:")
print(x)

print("Most frequent value:", most_frequent)
print("Number of times it occurs:", counts.max())
print("Indices:", indices)

Array x:
[1 2 3 4 5 1 2 1 1 1]
Most frequent value: 1
Number of times it occurs: 5
Indices: [0 5 7 8 9]


In [12]:
import numpy as np

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

# Find unique values and their counts
values, counts = np.unique(y, return_counts=True)

# Find the value with the highest frequency
most_frequent = values[np.argmax(counts)]

# Find the indices of the most frequent value
indices = np.where(y == most_frequent)[0]

print("Array y:")
print(y)

print("Most frequent value:", most_frequent)
print("Number of times it occurs:", counts.max())
print("Indices:", indices)

Array y:
[1 1 1 2 3 4 2 4 3 3]
Most frequent value: 1
Number of times it occurs: 3
Indices: [0 1 2]


In [6]:
import numpy as np

# Create the 2-D array
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Given 2-D Array:")
print(arr)

# Access 1st row, 2nd column
result = arr[0, 1]

print("\nElement at 1st row, 2nd column:")
print(result)

Given 2-D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Element at 1st row, 2nd column:
20


In [7]:
import numpy as np

# Create the 2-D array
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Given 2-D Array:")
print(arr)

# Access 3rd row, 1st column
result = arr[2, 0]

print("\nElement at 3rd row, 1st column:")
print(result)

Given 2-D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Element at 3rd row, 1st column:
70


In [8]:
import numpy as np

# Create a 1-D NumPy array with 25 evenly spaced numbers
mehakdeep_kaur = np.linspace(10, 100, 25)

print("1-D NumPy Array:")
print(mehakdeep_kaur)

# Print dimensions
print("\nDimensions of array:", mehakdeep_kaur.ndim)

# Print shape
print("Shape of array:", mehakdeep_kaur.shape)

# Print total number of elements
print("Total number of elements:", mehakdeep_kaur.size)

# Print data type
print("Data type of elements:", mehakdeep_kaur.dtype)

# Print total bytes consumed
print("Total bytes consumed:", mehakdeep_kaur.nbytes)

1-D NumPy Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions of array: 1
Shape of array: (25,)
Total number of elements: 25
Data type of elements: float64
Total bytes consumed: 200


In [13]:
# Convert 1-D array into a 25 x 1 array
reshaped_array = mehakdeep_kaur.reshape(25, 1)

print("After reshape(25, 1):")
print(reshaped_array)

# Find transpose
transpose_array = reshaped_array.T

print("\nTranspose of the array:")
print(transpose_array)

print("\nShape after transpose:", transpose_array.shape)

After reshape(25, 1):
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transpose of the array:
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]

Shape after transpose: (1, 25)


In [14]:
# Using T directly on the original 1-D array
transpose_using_T = mehakdeep_kaur.T

print("Transpose using T attribute:")
print(transpose_using_T)

print("\nShape using T:", transpose_using_T.shape)

Transpose using T attribute:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Shape using T: (25,)


In [9]:
import numpy as np

# Create a 2-D NumPy array with 3 rows and 4 columns
ucs420_mehakdeep_kaur = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original 2-D Array:")
print(ucs420_mehakdeep_kaur)

# Calculate mean
print("\nMean:")
print(np.mean(ucs420_mehakdeep_kaur))

# Calculate median
print("\nMedian:")
print(np.median(ucs420_mehakdeep_kaur))

# Find maximum value
print("\nMaximum:")
print(np.max(ucs420_mehakdeep_kaur))

# Find minimum value
print("\nMinimum:")
print(np.min(ucs420_mehakdeep_kaur))

# Find unique elements
print("\nUnique Elements:")
print(np.unique(ucs420_mehakdeep_kaur))

# Reshape the array to 4 rows and 3 columns
reshaped_ucs420_mehakdeep_kaur = ucs420_mehakdeep_kaur.reshape(4, 3)

print("\nReshaped Array (4 x 3):")
print(reshaped_ucs420_mehakdeep_kaur)

Original 2-D Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean:
43.333333333333336

Median:
37.5

Maximum:
90

Minimum:
10

Unique Elements:
[10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
